"""fix s in UserComplaintsOrm -> UserComplaintOrm

Revision ID: b423aac18d43
Revises: 4f46213e73a2
Create Date: 2026-05-17 16:00:37.992272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b423aac18d43"
down_revision: Union[str, Sequence[str], None] = "4f46213e73a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
