from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "4f46213e73a2"
down_revision: Union[str, Sequence[str], None] = "979f6cffa202"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gem_clarities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_colors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_inclusions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_origins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_shapes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_treatments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gem_types",
        sa.Column("image", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("short_description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=255), nullable=False),
        sa.Column("hash_password", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("organization", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("experience_years", sa.Integer(), nullable=False),
        sa.Column("profile_image", sa.String(), nullable=True),
        sa.Column("passport_photo", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "certificates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("BUY", "SELL", name="offertype"),
            nullable=False,
        ),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.Integer(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.Column("origin_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity",
            sa.Enum(
                "SINGLE_STONE", "PAIR", "LAYOUT", "PARCEL", name="quantitytype"
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("clarity_id", sa.Integer(), nullable=False),
        sa.Column("inclusion_id", sa.Integer(), nullable=False),
        sa.Column("treatment_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_total", sa.Float(), nullable=False),
        sa.Column("gem_location", sa.String(length=255), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["clarity_id"],
            ["gem_clarities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["gem_colors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inclusion_id"],
            ["gem_inclusions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["gem_origins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shape_id"],
            ["gem_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["treatment_id"],
            ["gem_treatments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["gem_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_complaints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complainant_id", sa.Integer(), nullable=False),
        sa.Column("defendant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["complainant_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["defendant_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_restrictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("no_private_message", sa.Boolean(), nullable=False),
        sa.Column("no_reply_to_requests", sa.Boolean(), nullable=False),
        sa.Column("no_create_requests", sa.Boolean(), nullable=False),
        sa.Column("max_3_messages_per_day", sa.Boolean(), nullable=False),
        sa.Column("max_1_message_per_day", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "request_type",
            sa.Enum("BUY", "SELL", name="requesttype"),
            nullable=False,
        ),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.Integer(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.Column("origin_id", sa.Integer(), nullable=False),
        sa.Column(
            "quantity",
            sa.Enum(
                "SINGLE_STONE", "PAIR", "LAYOUT", "PARCEL", name="quantitytype"
            ),
            nullable=False,
        ),
        sa.Column("weight_from", sa.Integer(), nullable=False),
        sa.Column("weight_to", sa.Integer(), nullable=False),
        sa.Column("dimension_from", sa.Integer(), nullable=False),
        sa.Column("dimension_to", sa.Integer(), nullable=False),
        sa.Column("clarity_id", sa.Integer(), nullable=False),
        sa.Column("inclusion_id", sa.Integer(), nullable=False),
        sa.Column("inclusion_note", sa.String(length=500), nullable=True),
        sa.Column("treatment_id", sa.Integer(), nullable=False),
        sa.Column("price_from", sa.Float(), nullable=False),
        sa.Column("price_to", sa.Float(), nullable=False),
        sa.Column("price_total_from", sa.Float(), nullable=False),
        sa.Column("price_total_to", sa.Float(), nullable=False),
        sa.Column(
            "additional_information", sa.String(length=1000), nullable=True
        ),
        sa.Column("gem_location", sa.String(length=255), nullable=False),
        sa.Column("certificate", sa.Integer(), nullable=True),
        sa.Column(
            "request_duration",
            sa.Enum(
                "HOURLY", "DAILY", "WEEKLY", "MONTHLY", name="requestduration"
            ),
            nullable=False,
        ),
        sa.Column("is_hide_profile", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["certificate"],
            ["certificates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["clarity_id"],
            ["gem_clarities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["gem_colors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inclusion_id"],
            ["gem_inclusions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_id"],
            ["gem_origins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shape_id"],
            ["gem_shapes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["treatment_id"],
            ["gem_treatments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["gem_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offer_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "request_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_images")
    op.drop_table("offer_images")
    op.drop_table("requests")
    op.drop_table("user_restrictions")
    op.drop_table("user_levels")
    op.drop_table("user_complaints")
    op.drop_table("offers")
    op.drop_table("certificates")
    op.drop_table("users")
    op.drop_table("gem_types")
    op.drop_table("gem_treatments")
    op.drop_table("gem_shapes")
    op.drop_table("gem_origins")
    op.drop_table("gem_inclusions")
    op.drop_table("gem_colors")
    op.drop_table("gem_clarities")
    # ### end Alembic commands ###
